name: "Kubernetes config file generator"
description: "Generate Kubernetes config file for the service account"
inputs:
  workdir:
    description: "Kubernetes config file directory."
    required: false
    default: "~/.kube"
  kubeconfig:
    description: "kubeconfig string"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "anchor"
  color: "blue"
