# This is a basic workflow to help you get started with Actions
name: "Generate Kubernetes config file for the service account"

# Controls when the action will run.
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy-dev-slot"
  deploy-dev-slot:
    name: kubeconfig generator
    env:
      NAMESPACE: 'dev'
    runs-on: ubuntu-18.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Test step
      - name: generating kubeconfig
        uses: InfraWay/generate-kube-config@main
        with:
          caData: "CADATA____"
          host: "https://HOST.com"
          clusterName: "CLUSTERNAME_____"
          namespace: ${{ env.NAMESPACE }}
          serviceAccountName: "SANAME____"
          serviceAccountToken: "SATOKEN____"
      - name: View kubeconfig
        run: echo "$(cat kube/config)"


